version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: plataforma_mysql
    restart: always
    env_file:
      - .env.db
    ports:
      - "3307:3306"
    volumes:
      - ./src/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql